### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by StefanChivoiu** [andreeabrezuica/Botani-Talk#1]
Upload documentation pls!

**Comment by StefanChivoiu** [comment]
![WhatsApp Image 2023-10-28 at 14 15 49_0615e436](https://github.com/andreeabrezuica/Botani-Talk/assets/149241120/665db987-7d5b-4c0e-93c1-f87e0d856c40)
![WhatsApp Image 2023-10-28 at 14 15 45_5145c0ef](https://github.com/andreeabrezuica/Botani-Talk/assets/149241120/5beb72ac-8e86-4743-98d5-cffd171eaf87)

**Comment by StefanChivoiu** [comment]
Will edit later with the new updates!

**Comment by WaruSpirit** [comment]
https://www.tinkercad.com/things/kjxV0FQRN1H-botani-talk
Link to Tinkercad project.
