### ISSUE TITLE
Implement PWM for Pump

### ISSUE THREAD

**Issue by StefanChivoiu** [andreeabrezuica/Botani-Talk#17]
The new pump is a stepper motor, with its own module. We need to implement Pulse-Width-Modulation so it works as desired.

**Comment by VortexFeri** [comment]
@WaruSpirit 
New pump requires 5 or 6 wires: 
- 12V for motor drive (5V works too, but only if the Arduino is supplied with 12V from an external battery)
- 5V for motor logic
- GND
- IN3 and IN4 for spin direction (we might get it over with just IN4 as we won't reverse the motor)
- ENB (PWM-capable pin) for speed control
